using UnityEngine;

namespace HoverCar.Data
{
    [CreateAssetMenu(fileName = "GravitySourceProfile", menuName = "HoverCar/Data/Gravity Source Profile")]
    public class GravitySourceProfile : ScriptableObject
    {
        [Header("Metadata")]
        [SerializeField]
        private string displayName = "Default Gravity";

        [Header("Gravity Settings")]
        [Tooltip("Base strength of the gravity force applied by this source.")]
        [SerializeField]
        private float gravityStrength = 9.81f;

        [Tooltip("Maximum range at which this gravity source will affect vehicles.")]
        [SerializeField]
        private float maxRange = 50f;

        [Tooltip("Defines how gravity falls off as distance increases (X: normalised distance, Y: multiplier).")]
        [SerializeField]
        private AnimationCurve falloff = AnimationCurve.EaseInOut(0f, 1f, 1f, 0f);

        [Header("Transform Overrides")]
        [Tooltip("Local offset applied to the gravity source when instantiated.")]
        [SerializeField]
        private Vector3 localOffset = Vector3.zero;

        [Tooltip("Whether objects should align to the surface normal generated by this gravity source.")]
        [SerializeField]
        private bool alignToSurfaceNormal = true;

        public string DisplayName => displayName;
        public float GravityStrength => gravityStrength;
        public float MaxRange => maxRange;
        public AnimationCurve Falloff => falloff;
        public Vector3 LocalOffset => localOffset;
        public bool AlignToSurfaceNormal => alignToSurfaceNormal;
    }
}
